language: node_js
sudo: false
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
node_js:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
notifications:
  email:
    recipients:
      - kmz111@gmail.com
    on_success: change
    on_failure: change
